apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: facimate
spec:
  selector:
    matchLabels:
      app: facimate-core
  replicas: 3
  template:
    metadata:
      labels:
        app: facimate-core
    spec:
      containers:
        - name: faci-core
          image: kishorelf/facimate:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
