apiVersion: apps/v1
kind: Deployment
metadata:
  name: facimategke
  namespace: default
spec:
  selector:
    matchLabels:
      app: facimate
  replicas: 1
  template:
    metadata:
      labels:
        app: facimate
    spec:
      containers:
        - name: facimategke
          image: 192.168.1.30:8082/facimate-gke:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: NEXUS_USERNAME
              value: "admin"
            - name: NEXUS_PASSWORD
              value: "lfadmin"
